# Generated by Django 3.1.5 on 2021-02-08 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isDriver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RideInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('startPoint', models.CharField(max_length=32)),
                ('endPoint', models.CharField(max_length=32)),
                ('memberNumber', models.IntegerField()),
                ('specialText', models.TextField(blank=True, default='')),
                ('isConfirmed', models.BooleanField(default=False)),
                ('driverWho', models.CharField(max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=32)),
                ('licenseNumber', models.CharField(max_length=32)),
                ('containNumber', models.IntegerField()),
                ('specialText', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userinfo')),
            ],
        ),
    ]
