# Generated by Django 3.1.5 on 2021-02-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideinfo',
            name='isSharable',
            field=models.BooleanField(default=False),
        ),
    ]
