# Generated by Django 3.1.5 on 2021-02-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rideinfo_issharable'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideinfo',
            name='sharer',
            field=models.ManyToManyField(related_name='sharer', to='login.UserInfo'),
        ),
        migrations.AlterField(
            model_name='rideinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login.userinfo'),
        ),
    ]
