# Generated by Django 3.1.5 on 2021-01-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210131_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='passsword',
            new_name='password',
        ),
    ]
