# Generated by Django 3.1.5 on 2021-02-06 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rideinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rideinfo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
