# Generated by Django 3.1.5 on 2021-02-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210206_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideinfo',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
