# Generated by Django 3.1.5 on 2021-02-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rideinfo_isconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideinfo',
            name='driverName',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
