# Generated by Django 3.1.5 on 2021-02-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rideinfo_drivername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideinfo',
            old_name='driverName',
            new_name='driver_Name',
        ),
    ]
