# Generated by Django 3.1.5 on 2021-02-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210207_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideinfo',
            old_name='driver_Name',
            new_name='driverrrr',
        ),
    ]
