# Generated by Django 3.1.5 on 2021-02-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20210207_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideinfo',
            name='driverrrr',
            field=models.CharField(default='', max_length=32),
        ),
    ]
